### ISSUE TITLE
Question/Feature

### ISSUE THREAD

**Issue by Pilly170** [R3nt0n/bopscrk#1]
Hi
Is it possible to specify 2+ wordlists in the -w parameter?

**Comment by R3nt0n** [comment]
Hello and thanks for the question!

Yes, it's possible, you just have to introduce it comma-separated. If you run `bopscrk.py -h`, you got all the help information.

`usage: bopscrk.py [-h] [-i] [-w] [--min] [--max] [-c] [-l] [-n] [-a] [-A] [-x]
                  [-o]

Generates smart and powerful wordlists.

optional arguments:
  -h, --help         show this help message and exit
  -i, --interactive  interactive mode, the script will ask you about target
  -w                 words to combine comma-separated (non-interactive mode)
  --min              min length for the words to generate (default: 4)
  --max              max length for the words to generate (default: 32)
  -c, --case         enable case transformations
  -l, --leet         enable leet transformations
  -n                 max amount of words to combine each time (default: 2)
  -a , --artists     artists to search song lyrics (comma-separated)
  -A, --lyrics-all   enable all possible transforms with lyrics
  -x , --exclude     exclude all the words included in other wordlists
                     (several wordlists should be comma-separated)
  -o , --output      output file to save the wordlist (default: tmp.txt)
`
