### ISSUE TITLE
Problem under Windows 10 and Python 3.8/3.9 and Ubuntu3.8 Python 2.7

### ISSUE THREAD

**Issue by Heinz-Olaf** [r3nt0n/bopscrk#11]
The new version don't works under Windows 10 64bit with Python 3.8/3.9 and Linux Ubuntu 18.6 with Python 2.7.
The version 2.0/1.5 and 2.2 works good.
Last version:
![1](https://user-images.githubusercontent.com/29728109/97866187-bdbc1d80-1d0b-11eb-955a-242d892386e8.PNG)
Version 2.0/1.5:
![3](https://user-images.githubusercontent.com/29728109/97867287-daf1eb80-1d0d-11eb-9199-e0da4dbf96f4.PNG)
Version 2.2:
![2](https://user-images.githubusercontent.com/29728109/97869055-117d3580-1d11-11eb-8cf8-1844724007d4.PNG)

**Comment by r3nt0n** [comment]
The issue was solved with the last commit. Thanks @Heinz-Olaf :1st_place_medal:
