### ISSUE TITLE
Lyrics: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by noraj** [R3nt0n/bopscrk#2]
I install the 3 Requirements: python2 python2-requests python2-beautifulsoup4.

I tried to generate of wordlist based on lyrics:

```python
# python2 bopscrk.py -a disturbed --output ~/wordlist.txt
  [*] Looking for Disturbed's lyrics...
  [*] 3344 phrases found
Traceback (most recent call last):
  File "bopscrk.py", line 576, in <module>
    try: main()
  File "bopscrk.py", line 497, in main
    for phrase in ly_initials_wl:
TypeError: 'NoneType' object is not iterable
```

**Comment by R3nt0n** [comment]
It looks like he can't find any lyric in the database about Disturbed. I will try to catch this error and show the warning in another way, so the app doesn't crash. Thanks to report this issue!
