### ISSUE TITLE
Support different cases and files as input

### ISSUE THREAD

**Issue by Soussef24** [r3nt0n/bopscrk#24]

**Comment by r3nt0n** [comment]
The last commit should address the case issue.

Regarding the feature request to support files as input, I don't think it fits the purpose of this tool. However, if you really need to satisfy that use case, can be achieved with something like this:

```bash
bopscrk -w $(sed ':a;N;$!ba;s/\n/,/g' ./input-words.txt) ...
```

I hope it helps!
