### ISSUE TITLE
bopscrk error not run (python 2.7)

### ISSUE THREAD

**Issue by r3nt0n** [r3nt0n/bopscrk#26]
### Discussed in https://github.com/r3nt0n/bopscrk/discussions/25

<div type='discussions-op-text'>

<sup>Originally posted by **view99ok** March  8, 2023</sup>

```
(root㉿kaliq)-[/home/qq/Desktop/bopscrk]
└─# pip install bopscrk        
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f1845443190>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/bopscrk/
Collecting bopscrk
  Using cached bopscrk-2.4.5.tar.gz (39 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1NysUU/bopscrk/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1NysUU/bopscrk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-NU0LKl
         cwd: /tmp/pip-install-1NysUU/bopscrk/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named setuptools
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
                                                                                
┌──(root㉿kaliq)-[/home/qq/Desktop/bopscrk]
└─# git clone --recurse-submodules https://github.com/r3nt0n/bopscrk
Cloning into 'bopscrk'...
remote: Enumerating objects: 485, done.
remote: Counting objects: 100% (174/174), done.
remote: Compressing objects: 100% (91/91), done.
remote: Total 485 (delta 93), reused 135 (delta 80), pack-reused 311
Receiving objects: 100% (485/485), 11.17 MiB | 410.00 KiB/s, done.
Resolving deltas: 100% (259/259), done.
Submodule 'bopscrk/modules/lyricpass' (https://github.com/r3nt0n/lyricpass.git) registered for path 'bopscrk/modules/lyricpass'
Cloning into '/home/qq/Desktop/cupp/bopscrk/bopscrk/modules/lyricpass'...
remote: Enumerating objects: 157, done.        
remote: Counting objects: 100% (1/1), done.        
remote: Total 157 (delta 0), reused 0 (delta 0), pack-reused 156        
Receiving objects: 100% (157/157), 54.82 KiB | 431.00 KiB/s, done.
Resolving deltas: 100% (54/54), done.
Submodule path 'bopscrk/modules/lyricpass': checked out '6f1f6d74cc645ccf1a75225c84f68a18cd522f02'
                                                                                
┌──(root㉿kaliq)-[/home/qq/Desktop/bopscrk]
└─# bopscrk -i
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/bopscrk-2.4.5-py3.11.egg/bopscrk/bopscrk.py", line 16, in start
    from .modules import main
  File "/usr/local/lib/python3.11/dist-packages/bopscrk-2.4.5-py3.11.egg/bopscrk/modules/main.py", line 11, in <module>
    from . import banners
  File "/usr/local/lib/python3.11/dist-packages/bopscrk-2.4.5-py3.11.egg/bopscrk/modules/banners.py", line 10, in <module>
    from .transforms import *
  File "/usr/local/lib/python3.11/dist-packages/bopscrk-2.4.5-py3.11.egg/bopscrk/modules/transforms.py", line 9, in <module>
    from alive_progress import alive_bar
ModuleNotFoundError: No module named 'alive_progress'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/bopscrk", line 33, in <module>
    sys.exit(load_entry_point('bopscrk==2.4.5', 'console_scripts', 'bopscrk')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/bopscrk-2.4.5-py3.11.egg/bopscrk/bopscrk.py", line 20, in start
    from modules import main
ModuleNotFoundError: No module named 'modules'</div>
```

**Comment by r3nt0n** [comment]
@view99ok it looks like you are trying to execute it with Python 2.7, currently only Python 3+ is supported. Try the following:

```shell
pip3 install bopscrk
bopscrk -i
```

Alternatively:

```shell
git clone --recurse-submodules https://github.com/r3nt0n/bopscrk
cd bopscrk
pip3 install -r requirements.txt
python3 bopscrk.py -i
```

**Comment by view99ok** [comment]
(root㉿kaliq)-[/home/qq]
└─# pip3 install bopscrk
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
                                                                                
┌──(root㉿kaliq)-[/home/qq]
└─# bopscrk -i
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/bopscrk-2.4.5-py3.11.egg/bopscrk/bopscrk.py", line 16, in start
    from .modules import main
  File "/usr/local/lib/python3.11/dist-packages/bopscrk-2.4.5-py3.11.egg/bopscrk/modules/main.py", line 11, in <module>
    from . import banners
  File "/usr/local/lib/python3.11/dist-packages/bopscrk-2.4.5-py3.11.egg/bopscrk/modules/banners.py", line 10, in <module>
    from .transforms import *
  File "/usr/local/lib/python3.11/dist-packages/bopscrk-2.4.5-py3.11.egg/bopscrk/modules/transforms.py", line 9, in <module>
    from alive_progress import alive_bar
ModuleNotFoundError: No module named 'alive_progress'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/bopscrk", line 33, in <module>
    sys.exit(load_entry_point('bopscrk==2.4.5', 'console_scripts', 'bopscrk')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/bopscrk-2.4.5-py3.11.egg/bopscrk/bopscrk.py", line 20, in start
    from modules import main
ModuleNotFoundError: No module named 'modules'
                                                                                
┌──(root㉿kaliq)-[/home/qq]
└─# git clone --recurse-submodules https://github.com/r3nt0n/bopscrk
fatal: destination path 'bopscrk' already exists and is not an empty directory.
                                                                                
┌──(root㉿kaliq)-[/home/qq]
└─# cd bopscrk
                                                                                
┌──(root㉿kaliq)-[/home/qq/bopscrk]
└─# ls
bopscrk           img      MANIFEST.in  requirements.txt  setup.py
build_package.sh  LICENSE  README.md    setup.cfg
                                                                                
┌──(root㉿kaliq)-[/home/qq/bopscrk]
└─# pip3 install -r requirements.txt
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
                                                                                
┌──(root㉿kaliq)-[/home/qq/bopscrk]
└─# python3 bopscrk.py -i
python3: can't open file '/home/qq/bopscrk/bopscrk.py': [Errno 2] No such file or directory
                                                                                
┌──(root㉿kaliq)-[/home/qq/bopscrk]
└─#
