### ISSUE TITLE
Bopscrk not respecting input character cases

### ISSUE THREAD

**Issue by vertexgamer** [r3nt0n/bopscrk#30]
The input words always become lower-case in the output, even if case transforms are disabled.
It's a big issue since the user might want to only combine words "as they are" or have already a curated list of basic case transforms (like: **test Test TEST** ) and don't want to spend extra compute time for unlikely combinations, like: **test tEst teSt tesT TEst**........ you got the idea

**Comment by r3nt0n** [comment]
It should be fixed with the last commit. Let me know what you think, any feedback would be much appreciated!
