### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by noraj** [R3nt0n/bopscrk#4]
python 2 is deprecated and the support will be dropped soon so python support would be welcome

**Comment by kinsbrunner** [comment]
Hi,
Just downloaded the code and adjusted it to be run under Python3. Changes that need to be done are:
1. wrap the PRINT argument between brackets.
2. there are 2 OPEN calls where they are sent 'rb' and 'wb'; remove from both the 'b' which stands for binary. 
3. replace every call to RAW_INPUT by INPUT.

This should be enough!

**Comment by R3nt0n** [comment]
Hi @noraj and @kinsbrunner , check out the last contribution from @agoertz-fls , thanks to him the tool has beeing official upgraded to Python 3. I have created a branch which mantains Python 2 legacy support.

**Comment by noraj** [comment]
Updated it in BA: https://github.com/BlackArch/blackarch/pull/2793/files
