### ISSUE TITLE
Capital letters changed automatically to lowercase

### ISSUE THREAD

**Issue by thgg4r** [R3nt0n/bopscrk#7]
Running In interactive mode autochanges all capital words to lowercase.

Example: John,Doe,Github,Blue

Tried both ways using Y and N invoking Case Transformations. 

Output file will always only produce lowercase words

Example:
john
doe
github
blue

Not able to generate output in the following format:
John
Doe
Github
Blue

**Comment by JeffTadashi** [comment]
I found a problem in the code related to this. The line below is the end output of the interactive data collection (line 412):
```
return wordlist, minLength, maxLength, leet, case, nWords, artists, ly_all_transforms, exclude, outfile
```
However, line 427 which invokes the interactive data collection is below:
```
base_wordlist, minLength, maxLength, case, leet, nWords, artists, ly_all_transforms, exclude_wordlists, outfile = asks()
```
Notice that case and leet are swapped in the order. That means in the Interactive mode, the case question really sets the leet parameter, and vice versa.

When using the tool non-interactively, it seems to work as expected.

**Comment by R3nt0n** [comment]
I just fix the issue, all the credit should go to @JeffTadashi , who found the bug.

Thanks to both of you for collaborating on the project!
