### ISSUE TITLE
how do i create a wordlist that only have 2 numbers and the rest are lowercase alphabet and it's length should be 8 ? 

### ISSUE THREAD

**Issue by minanagehsalalma** [R3nt0n/bopscrk#8]

**Comment by nxnjz** [comment]
https://github.com/hashcat/maskprocessor would be more suitable for that.

**Comment by minanagehsalalma** [comment]
> https://github.com/hashcat/maskprocessor would be more suitable for that.

@nxnjz hmm so it be like 

?l?d?l?l?l?d?l?l

But i do need to redo it many times to ensure the two numbers are every where in the wordlist or the position of the mask doesn't matter ?

Also how can i output it to a wordlist ?

**Comment by R3nt0n** [comment]
As @nxnjz mentioned above, maybe this is not the most suitable tool to accomplish this task. As another recommendation, you can try crunch.

**Comment by minanagehsalalma** [comment]
> As @nxnjz mentioned above, maybe this is not the most suitable tool to accomplish this task. As another recommendation, you can try crunch.

nope crunch would never work this out .
